import { z } from 'zod';

/**
 * v1 property (column) types supported by the copilot database tools.
 *
 * `created-time` / `updated-time` are read-only projections of block
 * metadata — they can be reported by the reader but never written by
 * `encodeCell`/`database_update`. Formula/relation/rollup are out of scope.
 */
export type PropertyType =
  | 'title'
  | 'rich-text'
  | 'text'
  | 'select'
  | 'multi-select'
  | 'number'
  | 'progress'
  | 'checkbox'
  | 'date'
  | 'link'
  | 'created-time'
  | 'updated-time';

/** A single select/multi-select option, as reported to (and accepted from) the model. */
export interface OptionJSON {
  id: string;
  value: string;
  color?: string;
}

/** A database column, projected to plain JSON for the copilot tools. */
export interface ColumnJSON {
  id: string;
  name: string;
  type: PropertyType;
  options?: OptionJSON[];
}

/** A database row, projected to plain JSON for the copilot tools. */
export interface RowJSON {
  rowId: string;
  title: string;
  cells: Record<string, unknown>;
}

/** A single kanban group: the group's value and the row ids it contains, in order. */
export interface ViewGroupJSON {
  value: string;
  cardRowIds: string[];
}

/** A database view (table or kanban), projected to plain JSON for the copilot tools. */
export interface ViewJSON {
  id: string;
  name: string;
  mode: string;
  groupByColumnId?: string;
  groups?: ViewGroupJSON[];
}

/** A full database board, projected to plain JSON for the copilot tools. */
export interface BoardJSON {
  blockId: string;
  title: string;
  columns: ColumnJSON[];
  rows: RowJSON[];
  views: ViewJSON[];
}

/** Add a new column to the board. The column id is generated by the writer. */
export interface AddColumnOp {
  op: 'add_column';
  name: string;
  type: PropertyType;
  options?: { value: string; color?: string }[];
}

/** Rename and/or retype an existing column. */
export interface UpdateColumnOp {
  op: 'update_column';
  columnId: string;
  name?: string;
  type?: PropertyType;
}

/** Remove a column and purge its cells from every row. */
export interface DeleteColumnOp {
  op: 'delete_column';
  columnId: string;
}

/** Append a new row (optionally seeding cell values, keyed by column id). */
export interface AddRowOp {
  op: 'add_row';
  title: string;
  cells?: Record<string, unknown>;
}

/** Set a single cell's value (title column updates the row's text instead). */
export interface UpdateCellOp {
  op: 'update_cell';
  rowId: string;
  columnId: string;
  value: unknown;
}

/** Remove a row and its cells. */
export interface DeleteRowOp {
  op: 'delete_row';
  rowId: string;
}

/** Append a new view (table or kanban). Kanban views group by `groupByColumnId`. */
export interface AddViewOp {
  op: 'add_view';
  name: string;
  mode: string;
  groupByColumnId?: string;
}

/** Move a row into a (possibly new) kanban group within a view. */
export interface MoveCardOp {
  op: 'move_card';
  viewId: string;
  rowId: string;
  groupValue: string;
}

/** The 8 mutation ops a `database_update` batch may contain. */
export type DatabaseOp =
  | AddColumnOp
  | UpdateColumnOp
  | DeleteColumnOp
  | AddRowOp
  | UpdateCellOp
  | DeleteRowOp
  | AddViewOp
  | MoveCardOp;

const PropertyTypeSchema = z.enum([
  'title',
  'rich-text',
  'text',
  'select',
  'multi-select',
  'number',
  'progress',
  'checkbox',
  'date',
  'link',
  'created-time',
  'updated-time',
]);

const AddColumnOpSchema = z.object({
  op: z.literal('add_column'),
  name: z.string(),
  type: PropertyTypeSchema,
  options: z
    .array(z.object({ value: z.string(), color: z.string().optional() }))
    .optional(),
});

const UpdateColumnOpSchema = z.object({
  op: z.literal('update_column'),
  columnId: z.string(),
  name: z.string().optional(),
  type: PropertyTypeSchema.optional(),
});

const DeleteColumnOpSchema = z.object({
  op: z.literal('delete_column'),
  columnId: z.string(),
});

const AddRowOpSchema = z.object({
  op: z.literal('add_row'),
  title: z.string(),
  cells: z.record(z.string(), z.unknown()).optional(),
});

const UpdateCellOpSchema = z.object({
  op: z.literal('update_cell'),
  rowId: z.string(),
  columnId: z.string(),
  value: z.unknown(),
});

const DeleteRowOpSchema = z.object({
  op: z.literal('delete_row'),
  rowId: z.string(),
});

const AddViewOpSchema = z.object({
  op: z.literal('add_view'),
  name: z.string(),
  mode: z.string(),
  groupByColumnId: z.string().optional(),
});

const MoveCardOpSchema = z.object({
  op: z.literal('move_card'),
  viewId: z.string(),
  rowId: z.string(),
  groupValue: z.string(),
});

/** Zod schema for {@link DatabaseOp}, used by the `database_update` tool input. */
export const DatabaseOpSchema = z.discriminatedUnion('op', [
  AddColumnOpSchema,
  UpdateColumnOpSchema,
  DeleteColumnOpSchema,
  AddRowOpSchema,
  UpdateCellOpSchema,
  DeleteRowOpSchema,
  AddViewOpSchema,
  MoveCardOpSchema,
]);
